#!/bin/bash

DIR=`pwd`/`dirname $0`;

rm -rf $DIR/temp/*

rm $DIR/../composer.lock
cd $DIR/..
composer install --no-interaction --prefer-source

export KEEP_TEMP=1

$DIR/../vendor/bin/tester -p php $DIR -s -j 5 --colors 1 -c $DIR/config/php-unix.ini